sudo: false
language: python
python:
    - "2.7"

before_install:
- mkdir -p $HOME/bin
- wget https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-linux-amd64-1.2.1.tar.gz
- tar xvfz git-lfs-linux-amd64-1.2.1.tar.gz
- mv git-lfs-1.2.1/git-lfs $HOME/bin/git-lfs
- export PATH=$PATH:$HOME/bin/

install: pip install tox-travis
script: tox
